### ISSUE TITLE
onKVStoreUpdate parameter

### ISSUE THREAD

**Issue by spacevoyager03** [reboot0-de/se-tools#1]
The parameter passed to KVStoreUpdateEvent is the detail.event object instead of the detail.event.data object.

In the example code:
`console.log('Your kvstore-item with the key ${data.key} just got updated to: ', data.value);`

To access the key and value currently, you have to do
`console.log('Your kvstore-item with the key ${data.data.key} just got updated to: ', data.data.value);`

**Comment by reboot0-de** [comment]
This should be fixed with the latest update to match the example usage.
https://github.com/reboot0-de/se-tools/commit/733e88b0e8e206cc48ce3fbfdc57b5b22447a368#diff-3d52d849797c6244024ab9e4a9e6909b900e5925727de7351a547e74b518e8e3
