### ISSUE TITLE
Proposal of a follower role.

### ISSUE THREAD

**Issue by AFoeee** [reboot0-de/se-tools#4]
There seem to be the roles:

- broadcaster
- moderator
- vip
- subscriber
- staff

I would find a **follower** role handy for raffle widgets and other user participation widgets.

**Comment by reboot0-de** [comment]
Unfortunately there is no data for followers on the message object and it doesn't look like Twitch wants to add that.
Checking for followers would require asking the API for that data on each message and that is a bit overkill for this toolset.
